name: Build and release

on:
  push:
    branches:
      - '**'

    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: |
          yarn test

      - name: Build extension
        run: |
          yarn build

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Replace version in manifest.json
        uses: jacobtomlinson/gha-find-replace@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          find: "0.0.0"
          replace: ${{ steps.get_version.outputs.version-without-v }}
          include: "extension/manifest.json"

      - name: Archive extension
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          zip -r ${{ github.ref }}.zip .
        working-dir: extension

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: extension/${{ github.ref }}.zip
