name: Build and release

on:
  push:
    branches:
      - '**'

    tags:
      - v*

jobs:
  build:
#    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          yarn test

      - name: Build and generate NuGet package
        run: |
          yarn build
